import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { useEffect } from "react";
import bg from "../../../assets/faqbg.png";

const faqData = [
  {
    index: 1,
    question: "What is Student-IA and how does it work?",
    answer:
      "An intelligent educational assistant, Student-IA is a digital tool that helps students solve problems, write content, and better understand their courses.\n\nA personalized guide: It adapts to your needs, your level of study, and your academic goals.\n\nA time-saver: It provides quick and accurate answers, whether it’s for an exercise, research, or revision.",
  },
  {
    index: 2,
    question: "How can Student-IA help me improve my academic results?",
    answer:
      "Intelligent educational assistant, Student-IA is a digital tool that helps students solve problems.",
  },
  {
    index: 3,
    question:
      "Can I customize the AI-generated content so it’s closer to what I want to say?",
    answer:
      "Yes, you can easily edit and personalize the content generated by Student-IA.",
  },
  {
    index: 4,
    question: "Is there a free trial available for Student-IA?",
    answer:
      "Yes, Student-IA offers a free trial to let you explore its core features.",
  },
  {
    index: 5,
    question: "What types of content can I create with Student-IA?",
    answer:
      "You can create essays, study notes, summaries, reports, and much more with Student-IA.",
  },
];

export default function FAQSection() {
  return (
    <section
      className=" py-10 md:py-20 overflow-hidden px-4 bg-center bg-cover"
      style={{
        backgroundImage: `url(${bg})`,
      }}
    >
      <div>
        <h1 className="text-white text-center font-roboto text-4xl font-bold leading-normal mb-12">
          Personal Trainer FAQs
        </h1>
      </div>
      <div
        className="relative w-full max-w-3xl mx-auto z-10"
        data-aos="fade-up"
      >
        <Accordion
          type="single"
          collapsible
          defaultValue={`faq-${faqData[0].index}`}
          className="w-full space-y-2"
        >
          {faqData.map((item) => (
            <AccordionItem
              key={`faq-${item.index}`}
              value={`faq-${item.index}`}
              className="border border-[#36393B] rounded-lg bg-gradient-to-br from-[#2B2B5C]/30 to-[#1A1A3C]/30 backdrop-blur-md"
            >
              <AccordionTrigger className="text-white font-roboto text-[20px] font-semibold leading-normal px-4 py-3 hover:no-underline">
                {item.question}
              </AccordionTrigger>
              {item.answer && (
                <AccordionContent className="text-[#E8E8E8] font-open-sans text-[18px] font-normal leading-normal px-4 pb-4 whitespace-pre-line">
                  <div className="w-[95%] mx-auto border-t border-[#36393B] mb-4" />
                  {item.answer}
                </AccordionContent>
              )}
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
}
